# Reuse the matching generated visual for manual and motorized versions.
IMAGES={
'hero-luxury-curtains':'hero','intro-living-room':'hero','about-zeya-curtains':'linen',
'curtains-category':'collection-curtains-v2','blinds-category':'collection-blinds-v2','motorized-solutions':'collection-motorized-v2',
'contact-interior':'sheer','process-consultation':'consultation','fabric-consultation':'fabric',
'zeya-og-image':'hero','cta-dubai-interior':'hero',
'product-sheer-curtains':'sheer','product-blackout-curtains':'blackout','product-linen-curtains':'linen',
'product-velvet-curtains':'velvet','product-wave-curtains':'wave','product-pinch-pleat-curtains':'pleat',
'product-double-layered-curtains':'double-layered-curtains','product-motorized-curtains':'motorized-curtains',
'product-roller-blinds':'roller','product-zebra-blinds':'zebra','product-roman-blinds':'roman',
'product-venetian-blinds':'venetian','product-wooden-blinds':'wooden','product-faux-wood-blinds':'faux-wood',
'product-vertical-blinds':'vertical','product-honeycomb-blinds':'honeycomb',
'product-sunscreen-blinds':'sunscreen','product-motorized-blinds':'motorized-blinds',
'product-motorized-roller-blinds':'motorized-roller-blinds',
'product-motorized-zebra-blinds':'motorized-zebra-blinds','product-motorized-roman-blinds':'motorized-roman-blinds',
'product-motorized-blackout-blinds':'motorized-blackout-blinds','product-motorized-sheer-curtains':'motorized-sheer-curtains',
'product-motorized-double-curtains':'motorized-double-curtains','product-motorized-venetian-blinds':'motorized-venetian-blinds',
'product-motorized-vertical-blinds':'motorized-vertical-blinds','product-motorized-outdoor-zip-screens':'motorized-outdoor-zip-screens',
'product-motorized-curtain-tracks':'motorized-curtain-tracks','product-smart-window-automation':'smart-window-automation',
# Curtain accessories are not on the supplied chart; each one borrows the
# generated interior that shows the fitting or fabric it belongs to.
'accessories-category':'collection-accessories-v2','product-curtain-rods-poles':'curtain-rods-poles',
'product-curtain-tracks':'curtain-tracks','product-tiebacks-holdbacks':'tiebacks-holdbacks',
'product-curtain-rings-hooks':'curtain-rings-hooks','product-finials-end-caps':'finials-end-caps',
'product-pelmets-valances':'pelmets-valances','product-curtain-linings':'curtain-linings',
'product-motorized-accessories':'motorized-accessories',
'sector-villa':'sector-villa','sector-apartment':'sector-apartment',
'sector-living-room':'sector-living-room','sector-bedroom':'sector-bedroom',
'sector-dining':'sector-dining','sector-home-office':'sector-home-office',
'sector-majlis':'sector-majlis','sector-office':'sector-office',
'sector-hotel':'sector-hotel','sector-restaurant':'sector-restaurant',
'sector-retail':'sector-retail','sector-clinic':'sector-clinic'}
