#!/usr/bin/env python3
"""
Build the WordPress theme from the same source as the static site.

    python tools/build_theme.py

Copies the CSS/JS/images into zeya-theme/assets/, writes inc/icons.php from the
icon sprite, and turns each page body into a WordPress page template with asset
paths and internal links routed through get_template_directory_uri() and
permalinks. functions.php, header.php, footer.php, style.css, index.php,
page.php and 404.php are hand-written and are never overwritten here.
"""
import os
import re
import shutil

from PIL import Image

import build_pages
import page_content

ROOT = build_pages.ROOT
SITE = build_pages.SITE
THEME = os.path.join(ROOT, "zeya-theme")

PAGE_SLUGS = ("home", "about", "products", "process", "contact")

TEMPLATE_FILES = {
    "home": ("front-page.php", "Front Page", None),
    "about": ("page-about.php", "ZEYA About", "About"),
    "products": ("page-products.php", "ZEYA Products", "Products"),
    "process": ("page-process.php", "ZEYA Process", "Process"),
    "contact": ("page-contact.php", "ZEYA Contact", "Contact"),
}


# ------------------------------------------------------------------ assets --
def copy_assets():
    pairs = (
        (os.path.join(SITE, "css"), os.path.join(THEME, "assets", "css")),
        (os.path.join(SITE, "js"), os.path.join(THEME, "assets", "js")),
        (os.path.join(SITE, "assets", "images"), os.path.join(THEME, "assets", "images")),
        (os.path.join(SITE, "assets", "icons"), os.path.join(THEME, "assets", "icons")),
        (os.path.join(SITE, "assets", "fonts"), os.path.join(THEME, "assets", "fonts")),
    )
    for src, dst in pairs:
        if not os.path.isdir(src):
            continue
        if os.path.isdir(dst):
            assert os.path.commonpath([os.path.realpath(dst), os.path.realpath(THEME)]) == os.path.realpath(THEME)
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        print("  assets/%-8s %d file(s)" % (os.path.basename(dst), len(os.listdir(dst))))


def write_icon_sprite():
    inc = os.path.join(THEME, "inc")
    os.makedirs(inc, exist_ok=True)
    svg = build_pages.sprite()
    php = (
        "<?php\n"
        "/**\n"
        " * Inline icon sprite.\n"
        " *\n"
        " * Printed once per page by zeya_icon_sprite(); individual icons are\n"
        " * referenced with zeya_icon( 'name' ). Inlining keeps the icons free of an\n"
        " * extra request and avoids the cross-document <use> restrictions that an\n"
        " * external sprite file runs into.\n"
        " *\n"
        " * Generated by tools/build_theme.py from assets/icons/zeya-icons.svg.\n"
        " *\n"
        " * @package ZEYA\n"
        " */\n\n"
        "if ( ! defined( 'ABSPATH' ) ) {\n"
        "\texit;\n"
        "}\n"
        "?>\n" + svg + "\n"
    )
    with open(os.path.join(inc, "icons.php"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(php)
    print("  inc/icons.php")


# --------------------------------------------------------------- templates --
def to_php(body):
    """Rewrite a static page body into WordPress-ready PHP."""
    # Theme asset paths, escaped at the point of output.
    body = re.sub(
        r"assets/images/([\w.\-]+\.webp)",
        lambda m: "<?php echo esc_url( $zeya_images . '%s' ); ?>" % m.group(1),
        body,
    )

    # Internal page links, including ones carrying a fragment.
    def link(match):
        slug, frag = match.group(1), match.group(2) or ""
        slug = "home" if slug == "index" else slug
        return 'href="<?php echo esc_url( zeya_link( \'%s\' ) ); ?>%s"' % (slug, frag)

    body = re.sub(r'href="([a-z][a-z-]*)\.html([?#][\w=-]+)?"', link, body)
    return body


HEAD = """<?php
/**
{doc}
 *
 * @package ZEYA
 */

if ( ! defined( 'ABSPATH' ) ) {{
\texit;
}}

get_header();

// Base URL for this theme's images; every <img> below builds on it.
$zeya_images = zeya_asset( 'images/' );
?>
{body}
<?php
get_footer();
"""


def doc_block(name, template_name, description):
    lines = [" * " + description]
    if template_name:
        lines.append(" *")
        lines.append(" * Template Name: " + template_name)
    return "\n".join(lines)


DESCRIPTIONS = {
    "home": "Front page: hero, benefits strip, introduction split, product cards and quote banner.",
    "about": "About: split story section, value cards, quote banner and the 'how we work' split.",
    "products": "Products: page header, three category cards, curtain/blind/motorized panels and the dark strip.",
    "process": "Process: page header, consultation photograph, six-step timeline, gallery and closing line.",
    "contact": "Contact: enquiry copy, contact methods and the form card over the interior panel.",
}


def contact_form_wrapper(body):
    """Let Contact Form 7 / WPForms take over the form when one is configured."""
    start = body.index('<!-- Field names follow')
    end = body.index("</form>") + len("</form>")
    static_form = body[start:end]

    # Point the form at the configured endpoint, if there is one.
    static_form = static_form.replace(
        'action="" method="post" novalidate',
        'action="<?php echo esc_url( zeya_contact( \'formEndpoint\' ) ); ?>" method="post" novalidate'
    )

    replacement = (
        "<?php if ( zeya_has_form_plugin() ) : ?>\n"
        "          <?php echo do_shortcode( zeya_contact_form_shortcode() ); ?>\n"
        "        <?php else : ?>\n"
        "          " + static_form + "\n"
        "        <?php endif; ?>"
    )
    return body[:start] + replacement + body[end:]


def build_templates():
    bodies = page_content.render(build_pages.H)
    bodies.update(build_pages.catalog.render(build_pages.H))
    for key in bodies:
        if key not in TEMPLATE_FILES:
            TEMPLATE_FILES[key] = ("page-"+key+".php", "ZEYA "+key.replace("-"," ").title(), key)
            DESCRIPTIONS[key] = "Product collection and details."

    for slug in bodies:
        filename, template_name, _ = TEMPLATE_FILES[slug]
        body = bodies[slug]

        if slug == "contact":
            body = contact_form_wrapper(body)

        php = HEAD.format(
            doc=doc_block(slug, template_name if slug != "home" else None, DESCRIPTIONS[slug]),
            body=to_php(body).strip("\n"),
        )
        with open(os.path.join(THEME, filename), "w", encoding="utf-8", newline="\n") as fh:
            fh.write(php)
        print("  %-20s %6.1f KB" % (filename, len(php) / 1024.0))


def write_screenshot():
    """WordPress shows screenshot.png in Appearance → Themes (1200×900)."""
    shot = os.path.join(os.environ.get("TEMP", "/tmp"), "zeya_shots", "index-desktop.png")
    if not os.path.exists(shot):
        print("  screenshot.png  (skipped — run tools/shoot.js first)")
        return
    im = Image.open(shot).convert("RGB")
    im = im.crop((0, 0, im.width, min(im.height, int(im.width * 0.75))))
    im = im.resize((1200, 900), Image.LANCZOS)
    im.save(os.path.join(THEME, "screenshot.png"), "PNG", optimize=True)
    print("  screenshot.png")


def main():
    os.makedirs(THEME, exist_ok=True)
    print("Assets")
    copy_assets()
    write_icon_sprite()
    print("\nTemplates")
    build_templates()
    print("\nTheme chrome")
    write_screenshot()
    print("\nBuilt -> zeya-theme/")


if __name__ == "__main__":
    main()
